### ISSUE TITLE
Semantic Releases according to PM docs

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/actions#2]
https://github.com/semantic-release

**Comment by Harjot1Singh** [comment]
Only push the release/changelog/bump back after the build steps are complete, but carry out the bump before.

Do we want some separate steps for the different publish scenarios we handle?
- Frontend to gh-pages
- npm package publish
- docker packages

**Comment by bhajneet** [comment]
https://github.com/shabados/.github/wiki/Project-Management

**Comment by Harjot1Singh** [comment]
Should NOT run the beta workflow when `skip-next-release` is on the PR. To be added to PM docs.

**Comment by Harjot1Singh** [comment]
Done 👍
