### ISSUE TITLE
Change ESLint rule requiring line breaks at 72/n chars

### ISSUE THREAD

**Issue by bhajneet** [shabados/actions#5]
Since most viewers/editors can wrap lines in 2020, we probably don't need the eslint rule forcing us to make line breaks in our source code. This also helps with generating docs from source code without single line breaks.

_Originally posted by @bhajneet & @Harjot1Singh in https://github.com/ShabadOS/gurmukhi-utils/pull/150_

**Comment by Harjot1Singh** [comment]
I think we should keep the line break rule - it's not about line wrapping, it's just overall a better visual experience and encourages better practice to keep code lines shorter and more succinct

**Comment by bhajneet** [comment]
Should create an issue to fix gurmukhi utils readme being generated with short lines since they're line broken comments

**Comment by bhajneet** [comment]
Actually it renders fine on GitHub, just looks a bit odd in source code. Not a big deal.
