### ISSUE TITLE
disable max body length for commit messages

### ISSUE THREAD

**Issue by saihaj** [shabados/actions#9]
**Is your feature request related to a problem? Please describe.**
By default commmitlint doesn't let you write commit message body 100 chars. Sometimes that is not enough for message body. We disabled that in mobile repo https://github.com/shabados/mobile/commit/c0cf3999c791626dcb72379d2636fc1cf570473b.

**Describe the solution you'd like**
Disable `body-max-line-length` rule in commitlint config

**Comment by Harjot1Singh** [comment]
Will accept PR for this
